### ISSUE TITLE
This is very very very very very very very very very very very very very very very very very bad

### ISSUE THREAD

**Issue by 78a5** [EwyBoy/Clay-WorldGen#1]
78a5 is very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very dumb!

**Comment by EwyBoy** [comment]
okey, why?

**Comment by 78a5** [comment]
cause im lol

**Comment by Rushmead** [comment]
This guy sucks i recommend you close this ewy.

**Comment by EwyBoy** [comment]
nah
