### ISSUE TITLE
latest version not working on 1.8.8 according to Forge

### ISSUE THREAD

**Issue by MoonCutter2B** [EwyBoy/Clay-WorldGen#2]
I used Curse Forge to create a new 1.8.8. world (forge is version 1655).
I added Clay-Worldgen, but forge doesn't like it, says mod wants 1.8.9
The message says something like [1.8.9, 1.8.9] should that be {1.8.8, 1.8.9] or something?

**Comment by EwyBoy** [comment]
Okey thanks for info! I will fix it now.

**Comment by EwyBoy** [comment]
I think I managed to fixed it now. http://minecraft.curseforge.com/projects/clay-worldgen/files
