### ISSUE TITLE
Minor typo in cfg

### ISSUE THREAD

**Issue by Flamingdonut** [EwyBoy/Clay-WorldGen#3]
In clayworldgen.cfg

```
 # Sets the minimum vein size for a clay vein [range: 1 ~ 256, default: 22]
    I:"Maximum Vein Size"=22
```

should read

 # Sets the **maximum** vein size for a clay vein [range: 1 ~ 256, default: 22]
    I:"Maximum Vein Size"=22

**Comment by EwyBoy** [comment]
ohh, my bad. I will get this fixed. Thanks
