### ISSUE TITLE
Clay Gens in Void World

### ISSUE THREAD

**Issue by UnRealDinnerbone** [EwyBoy/Clay-WorldGen#4]
yes it's a bad but http://ss.unrealdinnerbone.x10.bz/2016-05-30_22-18-15.png

**Comment by EwyBoy** [comment]
So the clay generates in the stone in the void world or is it causing the stone to generate too?

**Comment by UnRealDinnerbone** [comment]
No there a void world option when making a world and the clay generate in it

**Comment by EwyBoy** [comment]
hmm okey, I will look into it.

**Comment by EwyBoy** [comment]
Fixed

**Comment by UnRealDinnerbone** [comment]
:O

**Comment by EwyBoy** [comment]
Only took me 4.5 years. No biggie ;-)
