### ISSUE TITLE
1.9/1.10 source (and 1.11 update)

### ISSUE THREAD

**Issue by HeldMyWaffles** [EwyBoy/Clay-WorldGen#6]
So I could update this mod to 1.11 so I can get it reeeaaally quick for my server (well once forge fully updates), but where's the source for 1.9/1.10?

**Comment by EwyBoy** [comment]
I have to wait for the Forge mappings for 1.11 before I start my updating.

**Comment by EwyBoy** [comment]
1.11 Released https://minecraft.curseforge.com/projects/clay-worldgen. 
I will upload all the source for all versions soon.

**Comment by HeldMyWaffles** [comment]
That was quicker than I thought 🐑 💨

**Comment by EwyBoy** [comment]
I am pretty quick indeed. Btw the source for 1.8 is just the same as for 1.9, 1.10, and 1.11

**Comment by HeldMyWaffles** [comment]
> Btw the source for 1.8 is just the same as for 1.9, 1.10, and 1.11

I guess updating isn't really hard then 😉

**Comment by EwyBoy** [comment]
nah, 1.8-1.11 haven't really changed much about how worldgen is done.
