### ISSUE TITLE
1.16.4 and Forge 35.0.X compatible Version?

### ISSUE THREAD

**Issue by cyberpunkbln** [EwyBoy/Clay-WorldGen#8]
Hello,
your mod doesn't works with the newest versions of minecraft and forge, it is possible to make an compatible version?
thx

**Comment by EwyBoy** [comment]
Yes I will get that fixed ASAP.

**Comment by cyberpunkbln** [comment]
thx cool

**Comment by EwyBoy** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/clay-worldgen/files/3116956

**Comment by cyberpunkbln** [comment]
thx
